#!/bin/bash
rm focmec.lst focmec.stdout focmec_*.out -f
# test which control file to use for stdin:
POLS=`cat focmec.dat | sed 's#.*\(.\)$#\1#'`
FILE=focmec.P
case $POLS in
    *R*) FILE=${FILE}_SH;;
    *L*) FILE=${FILE}_SH;;
esac
case $POLS in
    *F*) FILE=${FILE}_SV;;
    *B*) FILE=${FILE}_SV;;
esac
FILE=${FILE}.stdin
## iterate from few to many errors and break at first found solutions
for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
do
    cat $FILE | sed "s#XXX#$i#" | ./focmec__Linux__64bit > focmec.stdout
    echo "trying to find solution with $i P-Errors..."
    grep -v "nan" focmec.out.all | grep "      $i.0   " > focmec.out && echo "found solution with $i Errors." && exit 0
done
exit 1
