# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_qMainWindow_obsPyck(object):
    def setupUi(self, qMainWindow_obsPyck):
        qMainWindow_obsPyck.setObjectName(_fromUtf8("qMainWindow_obsPyck"))
        qMainWindow_obsPyck.resize(1225, 789)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qMainWindow_obsPyck.sizePolicy().hasHeightForWidth())
        qMainWindow_obsPyck.setSizePolicy(sizePolicy)
        qMainWindow_obsPyck.setMaximumSize(QtCore.QSize(2000, 2000))
        qMainWindow_obsPyck.setBaseSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        qMainWindow_obsPyck.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("obspyck.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qMainWindow_obsPyck.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(qMainWindow_obsPyck)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.qSplitter_vertical = QtGui.QSplitter(self.centralwidget)
        self.qSplitter_vertical.setOrientation(QtCore.Qt.Vertical)
        self.qSplitter_vertical.setHandleWidth(8)
        self.qSplitter_vertical.setObjectName(_fromUtf8("qSplitter_vertical"))
        self.qSplitter_horizontal = QtGui.QSplitter(self.qSplitter_vertical)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qSplitter_horizontal.sizePolicy().hasHeightForWidth())
        self.qSplitter_horizontal.setSizePolicy(sizePolicy)
        self.qSplitter_horizontal.setFrameShape(QtGui.QFrame.NoFrame)
        self.qSplitter_horizontal.setFrameShadow(QtGui.QFrame.Plain)
        self.qSplitter_horizontal.setOrientation(QtCore.Qt.Horizontal)
        self.qSplitter_horizontal.setHandleWidth(8)
        self.qSplitter_horizontal.setObjectName(_fromUtf8("qSplitter_horizontal"))
        self.layoutWidgetxx = QtGui.QWidget(self.qSplitter_horizontal)
        self.layoutWidgetxx.setObjectName(_fromUtf8("layoutWidgetxx"))
        self.leftVerticalLayout = QtGui.QVBoxLayout(self.layoutWidgetxx)
        self.leftVerticalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.leftVerticalLayout.setMargin(0)
        self.leftVerticalLayout.setSpacing(0)
        self.leftVerticalLayout.setObjectName(_fromUtf8("leftVerticalLayout"))
        self.qToolButton_clearAll = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_clearAll.sizePolicy().hasHeightForWidth())
        self.qToolButton_clearAll.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.qToolButton_clearAll.setFont(font)
        self.qToolButton_clearAll.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_clearAll.setStyleSheet(_fromUtf8(""))
        self.qToolButton_clearAll.setCheckable(False)
        self.qToolButton_clearAll.setObjectName(_fromUtf8("qToolButton_clearAll"))
        self.leftVerticalLayout.addWidget(self.qToolButton_clearAll)
        self.qToolButton_clearOrigMag = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_clearOrigMag.sizePolicy().hasHeightForWidth())
        self.qToolButton_clearOrigMag.setSizePolicy(sizePolicy)
        self.qToolButton_clearOrigMag.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_clearOrigMag.setObjectName(_fromUtf8("qToolButton_clearOrigMag"))
        self.leftVerticalLayout.addWidget(self.qToolButton_clearOrigMag)
        self.qToolButton_clearFocMec = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_clearFocMec.sizePolicy().hasHeightForWidth())
        self.qToolButton_clearFocMec.setSizePolicy(sizePolicy)
        self.qToolButton_clearFocMec.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_clearFocMec.setObjectName(_fromUtf8("qToolButton_clearFocMec"))
        self.leftVerticalLayout.addWidget(self.qToolButton_clearFocMec)
        spacerItem = QtGui.QSpacerItem(170, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.leftVerticalLayout.addItem(spacerItem)
        self.qToolButton_doHyp2000 = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_doHyp2000.sizePolicy().hasHeightForWidth())
        self.qToolButton_doHyp2000.setSizePolicy(sizePolicy)
        self.qToolButton_doHyp2000.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_doHyp2000.setObjectName(_fromUtf8("qToolButton_doHyp2000"))
        self.leftVerticalLayout.addWidget(self.qToolButton_doHyp2000)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.qToolButton_doNlloc = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_doNlloc.sizePolicy().hasHeightForWidth())
        self.qToolButton_doNlloc.setSizePolicy(sizePolicy)
        self.qToolButton_doNlloc.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_doNlloc.setObjectName(_fromUtf8("qToolButton_doNlloc"))
        self.horizontalLayout_3.addWidget(self.qToolButton_doNlloc)
        self.qComboBox_nllocModel = QtGui.QComboBox(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qComboBox_nllocModel.sizePolicy().hasHeightForWidth())
        self.qComboBox_nllocModel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.qComboBox_nllocModel.setFont(font)
        self.qComboBox_nllocModel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qComboBox_nllocModel.setStyleSheet(_fromUtf8(""))
        self.qComboBox_nllocModel.setObjectName(_fromUtf8("qComboBox_nllocModel"))
        self.qComboBox_nllocModel.addItem(_fromUtf8(""))
        self.qComboBox_nllocModel.addItem(_fromUtf8(""))
        self.qComboBox_nllocModel.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.qComboBox_nllocModel)
        self.leftVerticalLayout.addLayout(self.horizontalLayout_3)
        self.qToolButton_doFocMec = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_doFocMec.sizePolicy().hasHeightForWidth())
        self.qToolButton_doFocMec.setSizePolicy(sizePolicy)
        self.qToolButton_doFocMec.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_doFocMec.setObjectName(_fromUtf8("qToolButton_doFocMec"))
        self.leftVerticalLayout.addWidget(self.qToolButton_doFocMec)
        spacerItem1 = QtGui.QSpacerItem(170, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.leftVerticalLayout.addItem(spacerItem1)
        self.qToolButton_showMap = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_showMap.sizePolicy().hasHeightForWidth())
        self.qToolButton_showMap.setSizePolicy(sizePolicy)
        self.qToolButton_showMap.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_showMap.setCheckable(True)
        self.qToolButton_showMap.setObjectName(_fromUtf8("qToolButton_showMap"))
        self.leftVerticalLayout.addWidget(self.qToolButton_showMap)
        self.qToolButton_showFocMec = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_showFocMec.sizePolicy().hasHeightForWidth())
        self.qToolButton_showFocMec.setSizePolicy(sizePolicy)
        self.qToolButton_showFocMec.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_showFocMec.setCheckable(True)
        self.qToolButton_showFocMec.setObjectName(_fromUtf8("qToolButton_showFocMec"))
        self.leftVerticalLayout.addWidget(self.qToolButton_showFocMec)
        self.qToolButton_nextFocMec = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_nextFocMec.sizePolicy().hasHeightForWidth())
        self.qToolButton_nextFocMec.setSizePolicy(sizePolicy)
        self.qToolButton_nextFocMec.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_nextFocMec.setObjectName(_fromUtf8("qToolButton_nextFocMec"))
        self.leftVerticalLayout.addWidget(self.qToolButton_nextFocMec)
        self.qToolButton_showWadati = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_showWadati.sizePolicy().hasHeightForWidth())
        self.qToolButton_showWadati.setSizePolicy(sizePolicy)
        self.qToolButton_showWadati.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_showWadati.setCheckable(True)
        self.qToolButton_showWadati.setObjectName(_fromUtf8("qToolButton_showWadati"))
        self.leftVerticalLayout.addWidget(self.qToolButton_showWadati)
        spacerItem2 = QtGui.QSpacerItem(170, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.leftVerticalLayout.addItem(spacerItem2)
        self.qToolButton_getNextEvent = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_getNextEvent.sizePolicy().hasHeightForWidth())
        self.qToolButton_getNextEvent.setSizePolicy(sizePolicy)
        self.qToolButton_getNextEvent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_getNextEvent.setObjectName(_fromUtf8("qToolButton_getNextEvent"))
        self.leftVerticalLayout.addWidget(self.qToolButton_getNextEvent)
        self.qToolButton_updateEventList = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_updateEventList.sizePolicy().hasHeightForWidth())
        self.qToolButton_updateEventList.setSizePolicy(sizePolicy)
        self.qToolButton_updateEventList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_updateEventList.setObjectName(_fromUtf8("qToolButton_updateEventList"))
        self.leftVerticalLayout.addWidget(self.qToolButton_updateEventList)
        self.qToolButton_sendNewEvent = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_sendNewEvent.sizePolicy().hasHeightForWidth())
        self.qToolButton_sendNewEvent.setSizePolicy(sizePolicy)
        self.qToolButton_sendNewEvent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_sendNewEvent.setObjectName(_fromUtf8("qToolButton_sendNewEvent"))
        self.leftVerticalLayout.addWidget(self.qToolButton_sendNewEvent)
        self.qToolButton_replaceEvent = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_replaceEvent.sizePolicy().hasHeightForWidth())
        self.qToolButton_replaceEvent.setSizePolicy(sizePolicy)
        self.qToolButton_replaceEvent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_replaceEvent.setObjectName(_fromUtf8("qToolButton_replaceEvent"))
        self.leftVerticalLayout.addWidget(self.qToolButton_replaceEvent)
        self.qToolButton_deleteEvent = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_deleteEvent.sizePolicy().hasHeightForWidth())
        self.qToolButton_deleteEvent.setSizePolicy(sizePolicy)
        self.qToolButton_deleteEvent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_deleteEvent.setObjectName(_fromUtf8("qToolButton_deleteEvent"))
        self.leftVerticalLayout.addWidget(self.qToolButton_deleteEvent)
        self.qToolButton_saveEventLocally = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_saveEventLocally.sizePolicy().hasHeightForWidth())
        self.qToolButton_saveEventLocally.setSizePolicy(sizePolicy)
        self.qToolButton_saveEventLocally.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_saveEventLocally.setObjectName(_fromUtf8("qToolButton_saveEventLocally"))
        self.leftVerticalLayout.addWidget(self.qToolButton_saveEventLocally)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.qCheckBox_public = QtGui.QCheckBox(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qCheckBox_public.sizePolicy().hasHeightForWidth())
        self.qCheckBox_public.setSizePolicy(sizePolicy)
        self.qCheckBox_public.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qCheckBox_public.setObjectName(_fromUtf8("qCheckBox_public"))
        self.horizontalLayout_4.addWidget(self.qCheckBox_public)
        self.qCheckBox_sysop = QtGui.QCheckBox(self.layoutWidgetxx)
        self.qCheckBox_sysop.setText(_fromUtf8(""))
        self.qCheckBox_sysop.setObjectName(_fromUtf8("qCheckBox_sysop"))
        self.horizontalLayout_4.addWidget(self.qCheckBox_sysop)
        self.qLineEdit_sysopPassword = QtGui.QLineEdit(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qLineEdit_sysopPassword.sizePolicy().hasHeightForWidth())
        self.qLineEdit_sysopPassword.setSizePolicy(sizePolicy)
        self.qLineEdit_sysopPassword.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qLineEdit_sysopPassword.setAcceptDrops(False)
        self.qLineEdit_sysopPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.qLineEdit_sysopPassword.setObjectName(_fromUtf8("qLineEdit_sysopPassword"))
        self.horizontalLayout_4.addWidget(self.qLineEdit_sysopPassword)
        self.leftVerticalLayout.addLayout(self.horizontalLayout_4)
        self.qComboBox_eventType = QtGui.QComboBox(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qComboBox_eventType.sizePolicy().hasHeightForWidth())
        self.qComboBox_eventType.setSizePolicy(sizePolicy)
        self.qComboBox_eventType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qComboBox_eventType.setObjectName(_fromUtf8("qComboBox_eventType"))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.qComboBox_eventType.addItem(_fromUtf8(""))
        self.leftVerticalLayout.addWidget(self.qComboBox_eventType)
        spacerItem3 = QtGui.QSpacerItem(170, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.leftVerticalLayout.addItem(spacerItem3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.leftVerticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.qLabel_x_rel = QtGui.QLabel(self.layoutWidgetxx)
        self.qLabel_x_rel.setObjectName(_fromUtf8("qLabel_x_rel"))
        self.horizontalLayout_8.addWidget(self.qLabel_x_rel)
        self.qLabel_xdata_rel = QtGui.QLabel(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qLabel_xdata_rel.sizePolicy().hasHeightForWidth())
        self.qLabel_xdata_rel.setSizePolicy(sizePolicy)
        self.qLabel_xdata_rel.setMinimumSize(QtCore.QSize(50, 0))
        self.qLabel_xdata_rel.setBaseSize(QtCore.QSize(40, 0))
        self.qLabel_xdata_rel.setAutoFillBackground(False)
        self.qLabel_xdata_rel.setText(_fromUtf8(""))
        self.qLabel_xdata_rel.setObjectName(_fromUtf8("qLabel_xdata_rel"))
        self.horizontalLayout_8.addWidget(self.qLabel_xdata_rel)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.qLabel_y = QtGui.QLabel(self.layoutWidgetxx)
        self.qLabel_y.setObjectName(_fromUtf8("qLabel_y"))
        self.horizontalLayout_7.addWidget(self.qLabel_y)
        self.qLabel_ydata = QtGui.QLabel(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qLabel_ydata.sizePolicy().hasHeightForWidth())
        self.qLabel_ydata.setSizePolicy(sizePolicy)
        self.qLabel_ydata.setMinimumSize(QtCore.QSize(25, 0))
        self.qLabel_ydata.setBaseSize(QtCore.QSize(40, 0))
        self.qLabel_ydata.setText(_fromUtf8(""))
        self.qLabel_ydata.setObjectName(_fromUtf8("qLabel_ydata"))
        self.horizontalLayout_7.addWidget(self.qLabel_ydata)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8b = QtGui.QHBoxLayout()
        self.horizontalLayout_8b.setObjectName(_fromUtf8("horizontalLayout_8b"))
        self.qLabel_x_abs = QtGui.QLabel(self.layoutWidgetxx)
        self.qLabel_x_abs.setObjectName(_fromUtf8("qLabel_x_abs"))
        self.horizontalLayout_8b.addWidget(self.qLabel_x_abs)
        self.qLabel_xdata_abs = QtGui.QLabel(self.layoutWidgetxx)
        self.qLabel_xdata_abs.setMinimumSize(QtCore.QSize(160, 0))
        self.qLabel_xdata_abs.setText(_fromUtf8(""))
        self.qLabel_xdata_abs.setObjectName(_fromUtf8("qLabel_xdata_abs"))
        self.horizontalLayout_8b.addWidget(self.qLabel_xdata_abs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8b)
        self.leftVerticalLayout.addLayout(self.verticalLayout_2)
        self.qToolButton_debug = QtGui.QToolButton(self.layoutWidgetxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_debug.sizePolicy().hasHeightForWidth())
        self.qToolButton_debug.setSizePolicy(sizePolicy)
        self.qToolButton_debug.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_debug.setObjectName(_fromUtf8("qToolButton_debug"))
        self.leftVerticalLayout.addWidget(self.qToolButton_debug)
        self.qWidget_mpl = QtGui.QWidget(self.qSplitter_horizontal)
        self.qWidget_mpl.setObjectName(_fromUtf8("qWidget_mpl"))
        self.qVBoxLayout_mpl = QtGui.QVBoxLayout(self.qWidget_mpl)
        self.qVBoxLayout_mpl.setObjectName(_fromUtf8("qVBoxLayout_mpl"))
        self.qMplCanvas = QMplCanvas(self.qWidget_mpl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(99)
        sizePolicy.setVerticalStretch(99)
        sizePolicy.setHeightForWidth(self.qMplCanvas.sizePolicy().hasHeightForWidth())
        self.qMplCanvas.setSizePolicy(sizePolicy)
        self.qMplCanvas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.qMplCanvas.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.qMplCanvas.setMouseTracking(True)
        self.qMplCanvas.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.qMplCanvas.setObjectName(_fromUtf8("qMplCanvas"))
        self.qVBoxLayout_mpl.addWidget(self.qMplCanvas)
        self.qSplitter_horizontal_new = QtGui.QSplitter(self.qWidget_mpl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qSplitter_horizontal_new.sizePolicy().hasHeightForWidth())
        self.qSplitter_horizontal_new.setSizePolicy(sizePolicy)
        self.qSplitter_horizontal_new.setFrameShape(QtGui.QFrame.NoFrame)
        self.qSplitter_horizontal_new.setFrameShadow(QtGui.QFrame.Plain)
        self.qSplitter_horizontal_new.setOrientation(QtCore.Qt.Horizontal)
        self.qSplitter_horizontal_new.setHandleWidth(8)
        self.qSplitter_horizontal_new.setObjectName(_fromUtf8("qSplitter_horizontal_new"))
        self.xxx = QtGui.QWidget(self.qSplitter_horizontal_new)
        self.xxx.setObjectName(_fromUtf8("xxx"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.xxx)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.qToolButton_sort_abc = QtGui.QToolButton(self.xxx)
        self.qToolButton_sort_abc.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_sort_abc.setObjectName(_fromUtf8("qToolButton_sort_abc"))
        self.verticalLayout_6.addWidget(self.qToolButton_sort_abc)
        self.qToolButton_sort_distance = QtGui.QToolButton(self.xxx)
        self.qToolButton_sort_distance.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_sort_distance.setObjectName(_fromUtf8("qToolButton_sort_distance"))
        self.verticalLayout_6.addWidget(self.qToolButton_sort_distance)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.VerticalLayout = QtGui.QVBoxLayout()
        self.VerticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.VerticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.VerticalLayout.setSpacing(6)
        self.VerticalLayout.setObjectName(_fromUtf8("VerticalLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.qToolButton_previousStream = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_previousStream.sizePolicy().hasHeightForWidth())
        self.qToolButton_previousStream.setSizePolicy(sizePolicy)
        self.qToolButton_previousStream.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_previousStream.setArrowType(QtCore.Qt.LeftArrow)
        self.qToolButton_previousStream.setObjectName(_fromUtf8("qToolButton_previousStream"))
        self.horizontalLayout_13.addWidget(self.qToolButton_previousStream)
        self.qLabel_streamNumber = QtGui.QLabel(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qLabel_streamNumber.sizePolicy().hasHeightForWidth())
        self.qLabel_streamNumber.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.qLabel_streamNumber.setFont(font)
        self.qLabel_streamNumber.setStyleSheet(_fromUtf8(""))
        self.qLabel_streamNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.qLabel_streamNumber.setObjectName(_fromUtf8("qLabel_streamNumber"))
        self.horizontalLayout_13.addWidget(self.qLabel_streamNumber)
        self.qToolButton_nextStream = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_nextStream.sizePolicy().hasHeightForWidth())
        self.qToolButton_nextStream.setSizePolicy(sizePolicy)
        self.qToolButton_nextStream.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_nextStream.setArrowType(QtCore.Qt.RightArrow)
        self.qToolButton_nextStream.setObjectName(_fromUtf8("qToolButton_nextStream"))
        self.horizontalLayout_13.addWidget(self.qToolButton_nextStream)
        self.VerticalLayout.addLayout(self.horizontalLayout_13)
        self.qComboBox_streamName = QtGui.QComboBox(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qComboBox_streamName.sizePolicy().hasHeightForWidth())
        self.qComboBox_streamName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.qComboBox_streamName.setFont(font)
        self.qComboBox_streamName.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qComboBox_streamName.setStyleSheet(_fromUtf8(""))
        self.qComboBox_streamName.setObjectName(_fromUtf8("qComboBox_streamName"))
        self.VerticalLayout.addWidget(self.qComboBox_streamName)
        self.horizontalLayout_6.addLayout(self.VerticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.qToolButton_overview = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_overview.sizePolicy().hasHeightForWidth())
        self.qToolButton_overview.setSizePolicy(sizePolicy)
        self.qToolButton_overview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_overview.setCheckable(True)
        self.qToolButton_overview.setObjectName(_fromUtf8("qToolButton_overview"))
        self.verticalLayout_3.addWidget(self.qToolButton_overview)
        self.qComboBox_phaseType = QtGui.QComboBox(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qComboBox_phaseType.sizePolicy().hasHeightForWidth())
        self.qComboBox_phaseType.setSizePolicy(sizePolicy)
        self.qComboBox_phaseType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qComboBox_phaseType.setObjectName(_fromUtf8("qComboBox_phaseType"))
        self.verticalLayout_3.addWidget(self.qComboBox_phaseType)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem4 = QtGui.QSpacerItem(1, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_9aa = QtGui.QVBoxLayout()
        self.verticalLayout_9aa.setObjectName(_fromUtf8("verticalLayout_9aa"))
        self.horizontalLayout_16aa = QtGui.QHBoxLayout()
        self.horizontalLayout_16aa.setObjectName(_fromUtf8("horizontalLayout_16aa"))
        self.qToolButton_ms = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_ms.sizePolicy().hasHeightForWidth())
        self.qToolButton_ms.setSizePolicy(sizePolicy)
        self.qToolButton_ms.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_ms.setCheckable(True)
        self.qToolButton_ms.setObjectName(_fromUtf8("qToolButton_ms"))
        self.horizontalLayout_16aa.addWidget(self.qToolButton_ms)
        self.verticalLayout_9aa.addLayout(self.horizontalLayout_16aa)
        self.horizontalLayout_14aa = QtGui.QHBoxLayout()
        self.horizontalLayout_14aa.setObjectName(_fromUtf8("horizontalLayout_14aa"))
        self.qLabel_waterlevel = QtGui.QLabel(self.xxx)
        self.qLabel_waterlevel.setObjectName(_fromUtf8("qLabel_waterlevel"))
        self.horizontalLayout_14aa.addWidget(self.qLabel_waterlevel)
        self.qDoubleSpinBox_waterlevel = QtGui.QDoubleSpinBox(self.xxx)
        self.qDoubleSpinBox_waterlevel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qDoubleSpinBox_waterlevel.setDecimals(0)
        self.qDoubleSpinBox_waterlevel.setMaximum(1000.0)
        self.qDoubleSpinBox_waterlevel.setSingleStep(5.0)
        self.qDoubleSpinBox_waterlevel.setProperty("value", 20.0)
        self.qDoubleSpinBox_waterlevel.setObjectName(_fromUtf8("qDoubleSpinBox_waterlevel"))
        self.horizontalLayout_14aa.addWidget(self.qDoubleSpinBox_waterlevel)
        self.verticalLayout_9aa.addLayout(self.horizontalLayout_14aa)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9aa)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.qToolButton_filter = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_filter.sizePolicy().hasHeightForWidth())
        self.qToolButton_filter.setSizePolicy(sizePolicy)
        self.qToolButton_filter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_filter.setCheckable(True)
        self.qToolButton_filter.setObjectName(_fromUtf8("qToolButton_filter"))
        self.horizontalLayout_17.addWidget(self.qToolButton_filter)
        self.qToolButton_rotateLQT = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_rotateLQT.sizePolicy().hasHeightForWidth())
        self.qToolButton_rotateLQT.setSizePolicy(sizePolicy)
        self.qToolButton_rotateLQT.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_rotateLQT.setCheckable(True)
        self.qToolButton_rotateLQT.setObjectName(_fromUtf8("qToolButton_rotateLQT"))
        self.horizontalLayout_17.addWidget(self.qToolButton_rotateLQT)
        self.qToolButton_rotateZRT = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_rotateZRT.sizePolicy().hasHeightForWidth())
        self.qToolButton_rotateZRT.setSizePolicy(sizePolicy)
        self.qToolButton_rotateZRT.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_rotateZRT.setCheckable(True)
        self.qToolButton_rotateZRT.setObjectName(_fromUtf8("qToolButton_rotateZRT"))
        self.horizontalLayout_17.addWidget(self.qToolButton_rotateZRT)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.qToolButton_trigger = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_trigger.sizePolicy().hasHeightForWidth())
        self.qToolButton_trigger.setSizePolicy(sizePolicy)
        self.qToolButton_trigger.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_trigger.setCheckable(True)
        self.qToolButton_trigger.setObjectName(_fromUtf8("qToolButton_trigger"))
        self.horizontalLayout_15.addWidget(self.qToolButton_trigger)
        self.qToolButton_arpicker = QtGui.QToolButton(self.xxx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qToolButton_arpicker.sizePolicy().hasHeightForWidth())
        self.qToolButton_arpicker.setSizePolicy(sizePolicy)
        self.qToolButton_arpicker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_arpicker.setArrowType(QtCore.Qt.NoArrow)
        self.qToolButton_arpicker.setObjectName(_fromUtf8("qToolButton_arpicker"))
        self.horizontalLayout_15.addWidget(self.qToolButton_arpicker)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        spacerItem5 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.qLabel_sta = QtGui.QLabel(self.xxx)
        self.qLabel_sta.setObjectName(_fromUtf8("qLabel_sta"))
        self.horizontalLayout_16.addWidget(self.qLabel_sta)
        self.qDoubleSpinBox_sta = QtGui.QDoubleSpinBox(self.xxx)
        self.qDoubleSpinBox_sta.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qDoubleSpinBox_sta.setSingleStep(0.1)
        self.qDoubleSpinBox_sta.setProperty("value", 0.5)
        self.qDoubleSpinBox_sta.setObjectName(_fromUtf8("qDoubleSpinBox_sta"))
        self.horizontalLayout_16.addWidget(self.qDoubleSpinBox_sta)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.qLabel_lta = QtGui.QLabel(self.xxx)
        self.qLabel_lta.setObjectName(_fromUtf8("qLabel_lta"))
        self.horizontalLayout_14.addWidget(self.qLabel_lta)
        self.qDoubleSpinBox_lta = QtGui.QDoubleSpinBox(self.xxx)
        self.qDoubleSpinBox_lta.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qDoubleSpinBox_lta.setProperty("value", 10.0)
        self.qDoubleSpinBox_lta.setObjectName(_fromUtf8("qDoubleSpinBox_lta"))
        self.horizontalLayout_14.addWidget(self.qDoubleSpinBox_lta)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        spacerItem6 = QtGui.QSpacerItem(1, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_12)
        spacerItem7 = QtGui.QSpacerItem(1, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.qVBoxLayout_mpl.addWidget(self.qSplitter_horizontal_new)
        self.qSplitter_horizontal_new2 = QtGui.QSplitter(self.qWidget_mpl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qSplitter_horizontal_new2.sizePolicy().hasHeightForWidth())
        self.qSplitter_horizontal_new2.setSizePolicy(sizePolicy)
        self.qSplitter_horizontal_new2.setFrameShape(QtGui.QFrame.NoFrame)
        self.qSplitter_horizontal_new2.setFrameShadow(QtGui.QFrame.Plain)
        self.qSplitter_horizontal_new2.setOrientation(QtCore.Qt.Horizontal)
        self.qSplitter_horizontal_new2.setHandleWidth(8)
        self.qSplitter_horizontal_new2.setObjectName(_fromUtf8("qSplitter_horizontal_new2"))
        self.yyy = QtGui.QWidget(self.qSplitter_horizontal_new2)
        self.yyy.setObjectName(_fromUtf8("yyy"))
        self.horizontalLayout_2b = QtGui.QHBoxLayout(self.yyy)
        self.horizontalLayout_2b.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2b.setSpacing(6)
        self.horizontalLayout_2b.setObjectName(_fromUtf8("horizontalLayout_2b"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.qComboBox_filterType = QtGui.QComboBox(self.yyy)
        self.qComboBox_filterType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qComboBox_filterType.setObjectName(_fromUtf8("qComboBox_filterType"))
        self.qComboBox_filterType.addItem(_fromUtf8(""))
        self.qComboBox_filterType.addItem(_fromUtf8(""))
        self.qComboBox_filterType.addItem(_fromUtf8(""))
        self.qComboBox_filterType.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.qComboBox_filterType)
        self.qCheckBox_zerophase = QtGui.QCheckBox(self.yyy)
        self.qCheckBox_zerophase.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qCheckBox_zerophase.setObjectName(_fromUtf8("qCheckBox_zerophase"))
        self.horizontalLayout_11.addWidget(self.qCheckBox_zerophase)
        self.qCheckBox_50Hz = QtGui.QCheckBox(self.yyy)
        self.qCheckBox_50Hz.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qCheckBox_50Hz.setObjectName(_fromUtf8("qCheckBox_50Hz"))
        self.horizontalLayout_11.addWidget(self.qCheckBox_50Hz)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.qLabel_corners = QtGui.QLabel(self.yyy)
        self.qLabel_corners.setObjectName(_fromUtf8("qLabel_corners"))
        self.horizontalLayout_10.addWidget(self.qLabel_corners)
        self.qDoubleSpinBox_corners = QtGui.QDoubleSpinBox(self.yyy)
        self.qDoubleSpinBox_corners.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qDoubleSpinBox_corners.setDecimals(0)
        self.qDoubleSpinBox_corners.setMinimum(1.0)
        self.qDoubleSpinBox_corners.setMaximum(8.0)
        self.qDoubleSpinBox_corners.setProperty("value", 1.0)
        self.qDoubleSpinBox_corners.setObjectName(_fromUtf8("qDoubleSpinBox_corners"))
        self.horizontalLayout_10.addWidget(self.qDoubleSpinBox_corners)
        self.qLabel_lowpass = QtGui.QLabel(self.yyy)
        self.qLabel_lowpass.setObjectName(_fromUtf8("qLabel_lowpass"))
        self.horizontalLayout_10.addWidget(self.qLabel_lowpass)
        self.qDoubleSpinBox_highpass = QtGui.QDoubleSpinBox(self.yyy)
        self.qDoubleSpinBox_highpass.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qDoubleSpinBox_highpass.setAcceptDrops(False)
        self.qDoubleSpinBox_highpass.setMinimum(0.01)
        self.qDoubleSpinBox_highpass.setSingleStep(0.5)
        self.qDoubleSpinBox_highpass.setProperty("value", 1.0)
        self.qDoubleSpinBox_highpass.setObjectName(_fromUtf8("qDoubleSpinBox_highpass"))
        self.horizontalLayout_10.addWidget(self.qDoubleSpinBox_highpass)
        self.qLabel_highpass = QtGui.QLabel(self.yyy)
        self.qLabel_highpass.setObjectName(_fromUtf8("qLabel_highpass"))
        self.horizontalLayout_10.addWidget(self.qLabel_highpass)
        self.qDoubleSpinBox_lowpass = QtGui.QDoubleSpinBox(self.yyy)
        self.qDoubleSpinBox_lowpass.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qDoubleSpinBox_lowpass.setMinimum(0.01)
        self.qDoubleSpinBox_lowpass.setProperty("value", 20.0)
        self.qDoubleSpinBox_lowpass.setObjectName(_fromUtf8("qDoubleSpinBox_lowpass"))
        self.horizontalLayout_10.addWidget(self.qDoubleSpinBox_lowpass)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2b.addLayout(self.verticalLayout_5)
        self.horizontalLayout_6x = QtGui.QHBoxLayout()
        self.horizontalLayout_6x.setObjectName(_fromUtf8("horizontalLayout_6x"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.qToolButton_spectrogram = QtGui.QToolButton(self.yyy)
        self.qToolButton_spectrogram.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qToolButton_spectrogram.setCheckable(True)
        self.qToolButton_spectrogram.setObjectName(_fromUtf8("qToolButton_spectrogram"))
        self.horizontalLayout_18.addWidget(self.qToolButton_spectrogram)
        self.qCheckBox_spectrogramLog = QtGui.QCheckBox(self.yyy)
        self.qCheckBox_spectrogramLog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qCheckBox_spectrogramLog.setObjectName(_fromUtf8("qCheckBox_spectrogramLog"))
        self.horizontalLayout_18.addWidget(self.qCheckBox_spectrogramLog)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.qLabel_wlen = QtGui.QLabel(self.yyy)
        self.qLabel_wlen.setObjectName(_fromUtf8("qLabel_wlen"))
        self.horizontalLayout_19.addWidget(self.qLabel_wlen)
        self.qDoubleSpinBox_wlen = QtGui.QDoubleSpinBox(self.yyy)
        self.qDoubleSpinBox_wlen.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qDoubleSpinBox_wlen.setSuffix(_fromUtf8(""))
        self.qDoubleSpinBox_wlen.setMinimum(0.1)
        self.qDoubleSpinBox_wlen.setMaximum(99.99)
        self.qDoubleSpinBox_wlen.setSingleStep(0.1)
        self.qDoubleSpinBox_wlen.setProperty("value", 0.4)
        self.qDoubleSpinBox_wlen.setObjectName(_fromUtf8("qDoubleSpinBox_wlen"))
        self.horizontalLayout_19.addWidget(self.qDoubleSpinBox_wlen)
        self.qLabel_perlap = QtGui.QLabel(self.yyy)
        self.qLabel_perlap.setObjectName(_fromUtf8("qLabel_perlap"))
        self.horizontalLayout_19.addWidget(self.qLabel_perlap)
        self.qDoubleSpinBox_perlap = QtGui.QDoubleSpinBox(self.yyy)
        self.qDoubleSpinBox_perlap.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qDoubleSpinBox_perlap.setMaximum(0.99)
        self.qDoubleSpinBox_perlap.setSingleStep(0.05)
        self.qDoubleSpinBox_perlap.setProperty("value", 0.9)
        self.qDoubleSpinBox_perlap.setObjectName(_fromUtf8("qDoubleSpinBox_perlap"))
        self.horizontalLayout_19.addWidget(self.qDoubleSpinBox_perlap)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_6x.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2b.addLayout(self.horizontalLayout_6x)
        spacerItem8 = QtGui.QSpacerItem(1, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2b.addItem(spacerItem8)
        self.qVBoxLayout_mpl.addWidget(self.qSplitter_horizontal_new2)
        self.verticalLayoutWidget = QtGui.QWidget(self.qSplitter_horizontal)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.rightVerticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.rightVerticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.rightVerticalLayout.setSpacing(0)
        self.rightVerticalLayout.setObjectName(_fromUtf8("rightVerticalLayout"))
        self.qTextEdit_qml = QtGui.QTextEdit(self.verticalLayoutWidget)
        self.qTextEdit_qml.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qTextEdit_qml.sizePolicy().hasHeightForWidth())
        self.qTextEdit_qml.setSizePolicy(sizePolicy)
        self.qTextEdit_qml.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        self.qTextEdit_qml.setFont(font)
        self.qTextEdit_qml.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qTextEdit_qml.setAcceptDrops(False)
        self.qTextEdit_qml.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.qTextEdit_qml.setReadOnly(True)
        self.qTextEdit_qml.setObjectName(_fromUtf8("qTextEdit_qml"))
        self.rightVerticalLayout.addWidget(self.qTextEdit_qml)
        self.qPushButton_qml_update = QtGui.QPushButton(self.verticalLayoutWidget)
        self.qPushButton_qml_update.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qPushButton_qml_update.setObjectName(_fromUtf8("qPushButton_qml_update"))
        self.rightVerticalLayout.addWidget(self.qPushButton_qml_update)
        self.layoutWidget = QtGui.QWidget(self.qSplitter_vertical)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.qPlainTextEdit_stdout = QtGui.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qPlainTextEdit_stdout.sizePolicy().hasHeightForWidth())
        self.qPlainTextEdit_stdout.setSizePolicy(sizePolicy)
        self.qPlainTextEdit_stdout.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        self.qPlainTextEdit_stdout.setFont(font)
        self.qPlainTextEdit_stdout.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qPlainTextEdit_stdout.setAcceptDrops(False)
        self.qPlainTextEdit_stdout.setUndoRedoEnabled(False)
        self.qPlainTextEdit_stdout.setReadOnly(True)
        self.qPlainTextEdit_stdout.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.qPlainTextEdit_stdout.setObjectName(_fromUtf8("qPlainTextEdit_stdout"))
        self.horizontalLayout.addWidget(self.qPlainTextEdit_stdout)
        self.qPlainTextEdit_stderr = QtGui.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qPlainTextEdit_stderr.sizePolicy().hasHeightForWidth())
        self.qPlainTextEdit_stderr.setSizePolicy(sizePolicy)
        self.qPlainTextEdit_stderr.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        self.qPlainTextEdit_stderr.setFont(font)
        self.qPlainTextEdit_stderr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qPlainTextEdit_stderr.setAcceptDrops(False)
        self.qPlainTextEdit_stderr.setUndoRedoEnabled(False)
        self.qPlainTextEdit_stderr.setReadOnly(True)
        self.qPlainTextEdit_stderr.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.qPlainTextEdit_stderr.setObjectName(_fromUtf8("qPlainTextEdit_stderr"))
        self.horizontalLayout.addWidget(self.qPlainTextEdit_stderr)
        self.verticalLayout.addWidget(self.qSplitter_vertical)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        qMainWindow_obsPyck.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(qMainWindow_obsPyck)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        qMainWindow_obsPyck.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(qMainWindow_obsPyck)
        self.statusbar.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        qMainWindow_obsPyck.setStatusBar(self.statusbar)

        self.retranslateUi(qMainWindow_obsPyck)
        self.qComboBox_eventType.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(qMainWindow_obsPyck)

    def retranslateUi(self, qMainWindow_obsPyck):
        qMainWindow_obsPyck.setWindowTitle(_translate("qMainWindow_obsPyck", "ObsPyck", None))
        self.qToolButton_clearAll.setText(_translate("qMainWindow_obsPyck", "clear All", None))
        self.qToolButton_clearOrigMag.setText(_translate("qMainWindow_obsPyck", "clear Orig&&Mag", None))
        self.qToolButton_clearFocMec.setText(_translate("qMainWindow_obsPyck", "clear FocMec", None))
        self.qToolButton_doHyp2000.setText(_translate("qMainWindow_obsPyck", "do hyp2000", None))
        self.qToolButton_doNlloc.setText(_translate("qMainWindow_obsPyck", "do NLLoc", None))
        self.qComboBox_nllocModel.setItemText(0, _translate("qMainWindow_obsPyck", "BY", None))
        self.qComboBox_nllocModel.setItemText(1, _translate("qMainWindow_obsPyck", "RH", None))
        self.qComboBox_nllocModel.setItemText(2, _translate("qMainWindow_obsPyck", "UH", None))
        self.qToolButton_doFocMec.setText(_translate("qMainWindow_obsPyck", "do focmec", None))
        self.qToolButton_showMap.setText(_translate("qMainWindow_obsPyck", "show Map", None))
        self.qToolButton_showFocMec.setText(_translate("qMainWindow_obsPyck", "show FocMec", None))
        self.qToolButton_nextFocMec.setText(_translate("qMainWindow_obsPyck", "next FocMec", None))
        self.qToolButton_showWadati.setText(_translate("qMainWindow_obsPyck", "show Wadati", None))
        self.qToolButton_getNextEvent.setText(_translate("qMainWindow_obsPyck", "get Next Event", None))
        self.qToolButton_updateEventList.setText(_translate("qMainWindow_obsPyck", "update Event List", None))
        self.qToolButton_sendNewEvent.setText(_translate("qMainWindow_obsPyck", "send New Event", None))
        self.qToolButton_replaceEvent.setText(_translate("qMainWindow_obsPyck", "replace Event", None))
        self.qToolButton_deleteEvent.setText(_translate("qMainWindow_obsPyck", "delete Event", None))
        self.qToolButton_saveEventLocally.setText(_translate("qMainWindow_obsPyck", "save Event locally", None))
        self.qCheckBox_public.setText(_translate("qMainWindow_obsPyck", "public", None))
        self.qComboBox_eventType.setItemText(0, _translate("qMainWindow_obsPyck", "<event type>", None))
        self.qComboBox_eventType.setItemText(1, _translate("qMainWindow_obsPyck", "not existing", None))
        self.qComboBox_eventType.setItemText(2, _translate("qMainWindow_obsPyck", "not reported", None))
        self.qComboBox_eventType.setItemText(3, _translate("qMainWindow_obsPyck", "earthquake", None))
        self.qComboBox_eventType.setItemText(4, _translate("qMainWindow_obsPyck", "anthropogenic event", None))
        self.qComboBox_eventType.setItemText(5, _translate("qMainWindow_obsPyck", "collapse", None))
        self.qComboBox_eventType.setItemText(6, _translate("qMainWindow_obsPyck", "cavity collapse", None))
        self.qComboBox_eventType.setItemText(7, _translate("qMainWindow_obsPyck", "mine collapse", None))
        self.qComboBox_eventType.setItemText(8, _translate("qMainWindow_obsPyck", "building collapse", None))
        self.qComboBox_eventType.setItemText(9, _translate("qMainWindow_obsPyck", "explosion", None))
        self.qComboBox_eventType.setItemText(10, _translate("qMainWindow_obsPyck", "accidental explosion", None))
        self.qComboBox_eventType.setItemText(11, _translate("qMainWindow_obsPyck", "chemical explosion", None))
        self.qComboBox_eventType.setItemText(12, _translate("qMainWindow_obsPyck", "controlled explosion", None))
        self.qComboBox_eventType.setItemText(13, _translate("qMainWindow_obsPyck", "experimental explosion", None))
        self.qComboBox_eventType.setItemText(14, _translate("qMainWindow_obsPyck", "industrial explosion", None))
        self.qComboBox_eventType.setItemText(15, _translate("qMainWindow_obsPyck", "mining explosion", None))
        self.qComboBox_eventType.setItemText(16, _translate("qMainWindow_obsPyck", "quarry blast", None))
        self.qComboBox_eventType.setItemText(17, _translate("qMainWindow_obsPyck", "road cut", None))
        self.qComboBox_eventType.setItemText(18, _translate("qMainWindow_obsPyck", "blasting levee", None))
        self.qComboBox_eventType.setItemText(19, _translate("qMainWindow_obsPyck", "nuclear explosion", None))
        self.qComboBox_eventType.setItemText(20, _translate("qMainWindow_obsPyck", "induced or triggered event", None))
        self.qComboBox_eventType.setItemText(21, _translate("qMainWindow_obsPyck", "rock burst", None))
        self.qComboBox_eventType.setItemText(22, _translate("qMainWindow_obsPyck", "reservoir loading", None))
        self.qComboBox_eventType.setItemText(23, _translate("qMainWindow_obsPyck", "fluid injection", None))
        self.qComboBox_eventType.setItemText(24, _translate("qMainWindow_obsPyck", "fluid extraction", None))
        self.qComboBox_eventType.setItemText(25, _translate("qMainWindow_obsPyck", "crash", None))
        self.qComboBox_eventType.setItemText(26, _translate("qMainWindow_obsPyck", "plane crash", None))
        self.qComboBox_eventType.setItemText(27, _translate("qMainWindow_obsPyck", "train crash", None))
        self.qComboBox_eventType.setItemText(28, _translate("qMainWindow_obsPyck", "boat crash", None))
        self.qComboBox_eventType.setItemText(29, _translate("qMainWindow_obsPyck", "other event", None))
        self.qComboBox_eventType.setItemText(30, _translate("qMainWindow_obsPyck", "atmospheric event", None))
        self.qComboBox_eventType.setItemText(31, _translate("qMainWindow_obsPyck", "sonic boom", None))
        self.qComboBox_eventType.setItemText(32, _translate("qMainWindow_obsPyck", "sonic blast", None))
        self.qComboBox_eventType.setItemText(33, _translate("qMainWindow_obsPyck", "acoustic noise", None))
        self.qComboBox_eventType.setItemText(34, _translate("qMainWindow_obsPyck", "thunder", None))
        self.qComboBox_eventType.setItemText(35, _translate("qMainWindow_obsPyck", "avalanche", None))
        self.qComboBox_eventType.setItemText(36, _translate("qMainWindow_obsPyck", "snow avalanche", None))
        self.qComboBox_eventType.setItemText(37, _translate("qMainWindow_obsPyck", "debris avalanche", None))
        self.qComboBox_eventType.setItemText(38, _translate("qMainWindow_obsPyck", "hydroacoustic event", None))
        self.qComboBox_eventType.setItemText(39, _translate("qMainWindow_obsPyck", "ice quake", None))
        self.qComboBox_eventType.setItemText(40, _translate("qMainWindow_obsPyck", "slide", None))
        self.qComboBox_eventType.setItemText(41, _translate("qMainWindow_obsPyck", "landslide", None))
        self.qComboBox_eventType.setItemText(42, _translate("qMainWindow_obsPyck", "rockslide", None))
        self.qComboBox_eventType.setItemText(43, _translate("qMainWindow_obsPyck", "meteorite", None))
        self.qComboBox_eventType.setItemText(44, _translate("qMainWindow_obsPyck", "volcanic eruption", None))
        self.qLabel_x_rel.setText(_translate("qMainWindow_obsPyck", "x (rel):", None))
        self.qLabel_y.setText(_translate("qMainWindow_obsPyck", "y:", None))
        self.qLabel_x_abs.setText(_translate("qMainWindow_obsPyck", "x:", None))
        self.qToolButton_debug.setText(_translate("qMainWindow_obsPyck", "debug", None))
        self.qToolButton_sort_abc.setToolTip(_translate("qMainWindow_obsPyck", "sort streams alphabetically", None))
        self.qToolButton_sort_abc.setText(_translate("qMainWindow_obsPyck", "sort ABC", None))
        self.qToolButton_sort_distance.setToolTip(_translate("qMainWindow_obsPyck", "sort streams by epicentral distance", None))
        self.qToolButton_sort_distance.setText(_translate("qMainWindow_obsPyck", "sort Dist.", None))
        self.qToolButton_previousStream.setText(_translate("qMainWindow_obsPyck", "<", None))
        self.qLabel_streamNumber.setText(_translate("qMainWindow_obsPyck", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<  html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, l  i { white-space: pre-wrap; }\n"
"<  /style></head><body style=\" font-family:\'Monospace\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<  p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00/00</p></body></html>", None))
        self.qToolButton_nextStream.setText(_translate("qMainWindow_obsPyck", ">", None))
        self.qToolButton_overview.setText(_translate("qMainWindow_obsPyck", "Overview", None))
        self.qToolButton_ms.setText(_translate("qMainWindow_obsPyck", "m/s", None))
        self.qLabel_waterlevel.setText(_translate("qMainWindow_obsPyck", "w_lev", None))
        self.qToolButton_filter.setText(_translate("qMainWindow_obsPyck", "Filter", None))
        self.qToolButton_rotateLQT.setText(_translate("qMainWindow_obsPyck", "LQT", None))
        self.qToolButton_rotateZRT.setText(_translate("qMainWindow_obsPyck", "ZRT", None))
        self.qToolButton_trigger.setText(_translate("qMainWindow_obsPyck", "recSTALTA", None))
        self.qToolButton_arpicker.setText(_translate("qMainWindow_obsPyck", "arPicker", None))
        self.qLabel_sta.setText(_translate("qMainWindow_obsPyck", "STA", None))
        self.qLabel_lta.setText(_translate("qMainWindow_obsPyck", "LTA", None))
        self.qComboBox_filterType.setItemText(0, _translate("qMainWindow_obsPyck", "Bandpass", None))
        self.qComboBox_filterType.setItemText(1, _translate("qMainWindow_obsPyck", "Bandstop", None))
        self.qComboBox_filterType.setItemText(2, _translate("qMainWindow_obsPyck", "Lowpass", None))
        self.qComboBox_filterType.setItemText(3, _translate("qMainWindow_obsPyck", "Highpass", None))
        self.qCheckBox_zerophase.setText(_translate("qMainWindow_obsPyck", "Zero-Ph.", None))
        self.qCheckBox_50Hz.setText(_translate("qMainWindow_obsPyck", "50Hz", None))
        self.qLabel_corners.setText(_translate("qMainWindow_obsPyck", "Corn.", None))
        self.qLabel_lowpass.setText(_translate("qMainWindow_obsPyck", "Low C.", None))
        self.qLabel_highpass.setText(_translate("qMainWindow_obsPyck", "High C.", None))
        self.qToolButton_spectrogram.setText(_translate("qMainWindow_obsPyck", "Spectrogram", None))
        self.qCheckBox_spectrogramLog.setText(_translate("qMainWindow_obsPyck", "log", None))
        self.qLabel_wlen.setText(_translate("qMainWindow_obsPyck", "wlen", None))
        self.qLabel_perlap.setText(_translate("qMainWindow_obsPyck", "%lap", None))
        self.qPushButton_qml_update.setText(_translate("qMainWindow_obsPyck", "update QuakeML text", None))

from util import QMplCanvas
